### ISSUE TITLE
activity.json updates wrong value for closedIssuesThisMonth

### ISSUE THREAD

**Issue by patrikerikss0n** [sebgroup/sebgroup.github.io#11]
See latest update from this morning https://github.com/sebgroup/sebgroup.github.io/commit/f32bf418df39bb08d7fd5830853d0a8ba69c7247

```json
 {
    "stars": 56,
    "forks": 24,
    "openIssues": 195,
    "closedIssuesThisMonth": 0,
    "activeProjects": 13,
    "contributors": 56,
    "month": "March",
    "year": 2020
  }
```

It takes the closedIssuesThisMonth from projects.json which this morning was 0 (correctly as it's April 1st today) https://github.com/sebgroup/sebgroup.github.io/commit/6dfb3f14e6127e60ec4ff1cc0072ce7cc438e893

It should probably take the value from the last day of the month (the day before), even though that's not 100% correct either, as there could be issues closed _during_ the last day of the month.

**Comment by patrikerikss0n** [comment]
Did a manual quick fix in https://github.com/sebgroup/sebgroup.github.io/commit/ed36a34a3337c4f8f089a5ad49b6edf76c35a34b however we should fix this properly.

**Comment by stuart-webster-seb** [comment]
@patrikerikss0n, how about changing the schedule on which _data/projects.json is updated? Currently, it seems that it is scheduled to run at midnight (so effectively shortly afterwards) every night, according to the schedule defined in .github\workflows\nodejs.yml, and _data/activity.json is updated a few minutes afterwards on the first of the month. If we were to change the time that _data/projects.json is updated to half an hour earlier, we wouldn't need to add a special case to handle the first of the month in the appendNoOfIssuesClosed function in data-loaders\project-fetcher.js.

**Comment by stuart-webster-seb** [comment]
```diff
diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
index fbd986d..81358b5 100644
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -2,7 +2,7 @@ name: Update projects data
 
 on:   
   schedule:
-    - cron: '0 0 * * *'
+    - cron: '30 23 * * *'
 
 jobs:
   build:
```

**Comment by patrikerikss0n** [comment]
That sounds great @stuart-webster-seb 

Good job, I have approved the PR #12 so go ahead and merge it.
